name: projek2_aplikasi_todolist
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  awesome_dialog: ^3.2.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0
  google_fonts: any
  intl: any
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^30.2.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/NexToDo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
