// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQU2g19p39OEgbS1GUhc1VJBJeC9B1Os',
    appId: '1:5224017638:web:0150c97241fb193c085527',
    messagingSenderId: '5224017638',
    projectId: 'richo-app-todolist-firebase',
    authDomain: 'richo-app-todolist-firebase.firebaseapp.com',
    storageBucket: 'richo-app-todolist-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArHK5hX7hXZD8LSqakMER5sQ4WWdPRkco',
    appId: '1:5224017638:android:42a802718982e345085527',
    messagingSenderId: '5224017638',
    projectId: 'richo-app-todolist-firebase',
    storageBucket: 'richo-app-todolist-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKrBYNiWsfzORG50ikeej4hznhLkUq6mc',
    appId: '1:5224017638:ios:f8aa16ac9c4642f3085527',
    messagingSenderId: '5224017638',
    projectId: 'richo-app-todolist-firebase',
    storageBucket: 'richo-app-todolist-firebase.firebasestorage.app',
    iosBundleId: 'com.example.projek2AplikasiTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKrBYNiWsfzORG50ikeej4hznhLkUq6mc',
    appId: '1:5224017638:ios:f8aa16ac9c4642f3085527',
    messagingSenderId: '5224017638',
    projectId: 'richo-app-todolist-firebase',
    storageBucket: 'richo-app-todolist-firebase.firebasestorage.app',
    iosBundleId: 'com.example.projek2AplikasiTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJQU2g19p39OEgbS1GUhc1VJBJeC9B1Os',
    appId: '1:5224017638:web:04fd788d07d6b657085527',
    messagingSenderId: '5224017638',
    projectId: 'richo-app-todolist-firebase',
    authDomain: 'richo-app-todolist-firebase.firebaseapp.com',
    storageBucket: 'richo-app-todolist-firebase.firebasestorage.app',
  );
}
